---
# tasks file for minikube - Debian/Ubuntu Family

- name: EL Family | Downloading and setting up {{ minikube_app }} {{ minikube_version }}
  get_url:
    url: "{{ minikube_dl_url }}"
    dest: "{{ minikube_bin_path }}/{{ minikube_app }}"
    owner: "{{ mc_file_owner }}"
    group: "{{ mc_file_group }}"
    mode: "{{ mc_file_mode }}"
